### ISSUE TITLE
Python 3.5 is not supported

### ISSUE THREAD

**Issue by Victornovikov** [medvedev1088/ethereum-etl#16]
Executing
` python export_blocks_and_transactions.py --start-block 0 --end-block 500000 --ipc-path ~/.ethereum/geth.ipc --blocks-output blocks.csv --transactions-output transactions.csv
`
unfortunately results in an error
  File "export_blocks_and_transactions.py", line 5, in <module>
    from ethereumetl.jobs.export_blocks_job import ExportBlocksJob
  File "/home/vn/ethereum-etl/ethereumetl/jobs/export_blocks_job.py", line 7, in <module>
    from ethereumetl.mappers.block_mapper import EthBlockMapper
  File "/home/vn/ethereum-etl/ethereumetl/mappers/block_mapper.py", line 1, in <module>
    from ethereumetl.domain.block import EthBlock
  File "/home/vn/ethereum-etl/ethereumetl/domain/block.py", line 8
    self.number: int = None
               ^

**Comment by medvedev1088** [comment]
Hi @Victornovikov. What is the version of python that you use? Also please include the full error log.

**Comment by Victornovikov** [comment]
thanks a lot for a prompt response.
`python --version`
3.5.2

it is pretty much the full log.. just in case pasting _everything_ from my terminal window

(eth) vn@eth-node:~/ethereum-etl$ python export_blocks_and_transactions.py --start-block 0 --end-block 500000 --ipc-path ~/.ethereum/geth.ipc --blocks-output blocks.csv --transactions-output transactions.csv
Traceback (most recent call last):
  File "export_blocks_and_transactions.py", line 5, in <module>
    from ethereumetl.jobs.export_blocks_job import ExportBlocksJob
  File "/home/vn/ethereum-etl/ethereumetl/jobs/export_blocks_job.py", line 7, in <module>
    from ethereumetl.mappers.block_mapper import EthBlockMapper
  File "/home/vn/ethereum-etl/ethereumetl/mappers/block_mapper.py", line 1, in <module>
    from ethereumetl.domain.block import EthBlock
  File "/home/vn/ethereum-etl/ethereumetl/domain/block.py", line 8
    self.number: int = None
               ^
SyntaxError: invalid syntax

**Comment by medvedev1088** [comment]
Try upgrading to Python 3.6. Type annotations are not supported in python 3.5. I'll add support for python 3.5 later.

**Comment by Victornovikov** [comment]
Yep, all works now. Thanks!
Should have paid more attention to README.
