### ISSUE TITLE
Error during parsing of results running export_all.sh - Results from nohup.out below

### ISSUE THREAD

**Issue by jonjet** [medvedev1088/ethereum-etl#3]
2018-05-16 01:34:54 Exporting blocks 04600000-04699999 to output/start_block=04600000/end_block=04699999/blocks_rpc_output_04600000_04699999.json
2018-05-16 02:21:18 Extracting blocks 04600000-04699999 to output/start_block=04600000/end_block=04699999/blocks_04600000_04699999.csv
2018-05-16 02:21:18 Extracting transactions from blocks 04600000-04699999 to output/start_block=04600000/end_block=04699999/transactions_04600000_04699999.csv
2018-05-16 02:56:10 Exporting ERC20 transfers from blocks 04600000-04699999 to output/start_block=04600000/end_block=04699999/erc20_transfers_04600000_04699999.csv
Traceback (most recent call last):
  File "/home/user/miniconda3/lib/python3.6/site-packages/web3/providers/ipc.py", line 175, in make_request
    response = self.decode_rpc_response(raw_response)
  File "/home/user/miniconda3/lib/python3.6/site-packages/web3/providers/base.py", line 60, in decode_rpc_response
    return json.loads(to_text(response))
  File "/home/user/miniconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/user/miniconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/user/miniconda3/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 15302641 (char 15302640)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "export_erc20_transfers.py", line 40, in <module>
    events = event_filter.get_all_entries()
  File "/home/user/miniconda3/lib/python3.6/site-packages/web3/utils/filters.py", line 109, in get_all_entries
    log_entries = self._filter_valid_entries(self.web3.eth.getFilterLogs(self.filter_id))
  File "/home/user/miniconda3/lib/python3.6/site-packages/web3/eth.py", line 325, in getFilterLogs
    "eth_getFilterLogs", [filter_id],
  File "/home/user/miniconda3/lib/python3.6/site-packages/web3/manager.py", line 103, in request_blocking
    response = self._make_request(method, params)
  File "/home/user/miniconda3/lib/python3.6/site-packages/web3/manager.py", line 86, in _make_request
    return request_func(method, params)
  File "/home/user/miniconda3/lib/python3.6/site-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/user/miniconda3/lib/python3.6/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/home/user/miniconda3/lib/python3.6/site-packages/web3/middleware/attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/user/miniconda3/lib/python3.6/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/home/user/miniconda3/lib/python3.6/site-packages/web3/middleware/normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/user/miniconda3/lib/python3.6/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/user/miniconda3/lib/python3.6/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/home/user/miniconda3/lib/python3.6/site-packages/web3/providers/ipc.py", line 177, in make_request
    timeout.sleep(0)
  File "/home/user/miniconda3/lib/python3.6/site-packages/web3/utils/threads.py", line 68, in sleep
    self.check()
  File "/home/user/miniconda3/lib/python3.6/site-packages/web3/utils/threads.py", line 61, in check
    raise self
web3.utils.threads.Timeout: 300 seconds
2018-05-16 03:31:53 Exporting blocks 04600000-04699999 took 7019 seconds

**Comment by medvedev1088** [comment]
Thanks for reporting this issue. 

I also faced it while exporting 4600k-4699k blocks. At this period there was a peak with over 1 milling transfers on November 27 https://medium.com/@medvedev1088/exporting-and-analyzing-ethereum-blockchain-f5353414a94e

A quick workaround is to change  `ipc_batch_size=100` to `ipc_batch_size=10` in export_all.sh.

This issue should be mitigated when I fix this performance issue in web3py https://github.com/ethereum/web3.py/issues/842.  Additionally, there should be a try-catch in export_erc20_transfers.py for `Timeout` exception, followed by requesting the transfers with `batch_size=1`

**Comment by jonjet** [comment]
Thanks for the workaround. I've not tested this yet since I'm still loading the data job. Block 5200000-5299999 is having the same errors as well. 

I'll test these both 4600000-4699999 and 5200000-5299999 with batch size of 10 once I've completed the full job.

Log for reference:-

2018-05-17 02:14:00 Exporting blocks 05200000-05299999 to output/start_block=05200000/end_block=05299999/blocks_rpc_output_05200000_05299999.json
2018-05-17 03:03:15 Extracting blocks 05200000-05299999 to output/start_block=05200000/end_block=05299999/blocks_05200000_05299999.csv
2018-05-17 03:03:15 Extracting transactions from blocks 05200000-05299999 to output/start_block=05200000/end_block=05299999/transactions_05200000_05299999.csv
2018-05-17 03:41:46 Exporting ERC20 transfers from blocks 05200000-05299999 to output/start_block=05200000/end_block=05299999/erc20_transfers_05200000_05299999.csv
Traceback (most recent call last):
  File "/home/jetyap/miniconda3/lib/python3.6/site-packages/web3/providers/ipc.py", line 175, in make_request
    response = self.decode_rpc_response(raw_response)
  File "/home/jetyap/miniconda3/lib/python3.6/site-packages/web3/providers/base.py", line 60, in decode_rpc_response
    return json.loads(to_text(response))
  File "/home/jetyap/miniconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/jetyap/miniconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/jetyap/miniconda3/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 15232990 (char 15232989)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "export_erc20_transfers.py", line 40, in <module>
    events = event_filter.get_all_entries()
  File "/home/jetyap/miniconda3/lib/python3.6/site-packages/web3/utils/filters.py", line 109, in get_all_entries
    log_entries = self._filter_valid_entries(self.web3.eth.getFilterLogs(self.filter_id))
  File "/home/jetyap/miniconda3/lib/python3.6/site-packages/web3/eth.py", line 325, in getFilterLogs
    "eth_getFilterLogs", [filter_id],
  File "/home/jetyap/miniconda3/lib/python3.6/site-packages/web3/manager.py", line 103, in request_blocking
    response = self._make_request(method, params)
  File "/home/jetyap/miniconda3/lib/python3.6/site-packages/web3/manager.py", line 86, in _make_request
    return request_func(method, params)
  File "/home/jetyap/miniconda3/lib/python3.6/site-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/jetyap/miniconda3/lib/python3.6/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/home/jetyap/miniconda3/lib/python3.6/site-packages/web3/middleware/normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/jetyap/miniconda3/lib/python3.6/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/jetyap/miniconda3/lib/python3.6/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/home/jetyap/miniconda3/lib/python3.6/site-packages/web3/providers/ipc.py", line 177, in make_request
    timeout.sleep(0)
  File "/home/jetyap/miniconda3/lib/python3.6/site-packages/web3/utils/threads.py", line 68, in sleep
    self.check()
  File "/home/jetyap/miniconda3/lib/python3.6/site-packages/web3/utils/threads.py", line 61, in check
    raise self
web3.utils.threads.Timeout: 300 seconds
2018-05-17 05:26:33 Exporting blocks 05200000-05299999 took 11553 seconds

**Comment by jonjet** [comment]
I've left `ipc_batch_size=100` and changed the following parameters `export_erc20_batch_size=10` and both jobs completed successfully without any degradation in performance.

2018-05-18 06:01:01 Extracting transactions from blocks 04600000-04699999 to output/start_block=04600000/end_block=04699999/transactions_04600000_04699999.csv
2018-05-18 06:35:25 Exporting ERC20 transfers from blocks 04600000-04699999 to output/start_block=04600000/end_block=04699999/erc20_transfers_04600000_04699999.csv
2018-05-18 07:24:10 Exporting blocks 04600000-04699999 took 7740 seconds
2018-05-18 07:29:50 Exporting blocks 05200000-05299999 to output/start_block=05200000/end_block=05299999/blocks_rpc_output_05200000_05299999.json
2018-05-18 08:18:24 Extracting blocks 05200000-05299999 to output/start_block=05200000/end_block=05299999/blocks_05200000_05299999.csv
2018-05-18 08:18:24 Extracting transactions from blocks 05200000-05299999 to output/start_block=05200000/end_block=05299999/transactions_05200000_05299999.csv
2018-05-18 08:55:17 Exporting ERC20 transfers from blocks 05200000-05299999 to output/start_block=05200000/end_block=05299999/erc20_transfers_05200000_05299999.csv
2018-05-18 09:45:18 Exporting blocks 05200000-05299999 took 8128 seconds

**Comment by medvedev1088** [comment]
That's good news. I will reduce the default value for this parameter. I also optimized web3.py IPCProvider https://github.com/ethereum/web3.py/pull/849 so once they release a new version and I include it in this lib, ERC20 transfer export will be even faster.
