### ISSUE TITLE
Ran export_all command in Windows but only generated erc20_transfer csv

### ISSUE THREAD

**Issue by s2r3dswq** [medvedev1088/ethereum-etl#4]
Im running on windows and used the following command:
./export_all.sh -s 3000000 -e 4000000 -b 100000 -i '\\.\pipe\geth.ipc' -o output

following error occured:

2018-05-17 23:00:08 Exporting blocks 03000000-03099999 to output/start_block=03000000/end_block=03099999/blocks_rpc_output_03000000_03099999.json
Traceback (most recent call last):
  File "exchange_with_ipc.py", line 20, in <module>
    response = socket_exchange(args.ipc_path, ''.join(line_batch), args.ipc_timeout)
  File "C:\ethereum-etl\ethereumetl\socket_utils.py", line 10, in socket_exchange
    sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
AttributeError: module 'socket' has no attribute 'AF_UNIX'
Traceback (most recent call last):
  File "gen_blocks_rpc.py", line 32, in <module>
    output_file.write(json.dumps(data) + '\n')
OSError: [Errno 22] Invalid argument
2018-05-17 23:00:08 Extracting blocks 03000000-03099999 to output/start_block=03000000/end_block=03099999/blocks_03000000_03099999.csv
2018-05-17 23:00:08 Extracting transactions from blocks 03000000-03099999 to output/start_block=03000000/end_block=03099999/transactions_03000000_03099999.csv
2018-05-17 23:00:08 Exporting ERC20 transfers from blocks 03000000-03099999 to output/start_block=03000000/end_block=03099999/erc20_transfers_03000000_03099999.csv
2018-05-17 23:05:18 Exporting blocks 03000000-03099999 took 310 seconds

**Comment by medvedev1088** [comment]
@s2r3dswq I added support for Windows. Please help test when you have time. 

I tested with this command:

`./export_all.sh -s 0 -e 9999 -b 10000 -i '\\.\pipe\geth.ipc' -o output`

**Comment by s2r3dswq** [comment]
tested and working for export_all.sh on windows env
Thanks
