### ISSUE TITLE
Export Receipts failed 

### ISSUE THREAD

**Issue by shayanb** [medvedev1088/ethereum-etl#41]
After running the command to get transaction receipts:
```
sudo python3 export_receipts_and_logs.py --tx-hashes transactions.csv --ipc-path /mnt/volume/ethereum/geth.ipc --receipts-output receipts.csv
```
I got the following error:

```
Traceback (most recent call last):
  File "export_receipts_and_logs.py", line 35, in <module>
    job.run()
  File "/mnt/ethereum-etl/ethereumetl/jobs/base_job.py", line 7, in run
    self._end()
  File "/mnt/ethereum-etl/ethereumetl/jobs/export_receipts_job.py", line 58, in _end
    self.batch_work_executor.shutdown()
  File "/mnt/ethereum-etl/ethereumetl/executors/batch_work_executor.py", line 44, in shutdown
    self.executor.shutdown()
  File "/mnt/ethereum-etl/ethereumetl/executors/fail_safe_executor.py", line 16, in shutdown
    self._check_completed_futures()
  File "/mnt/ethereum-etl/ethereumetl/executors/fail_safe_executor.py", line 24, in _check_completed_futures
    future.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/mnt/ethereum-etl/ethereumetl/jobs/base_job.py", line 5, in run
    self._export()
  File "/mnt/ethereum-etl/ethereumetl/jobs/export_receipts_job.py", line 40, in _export
    self.batch_work_executor.execute(self.tx_hashes_iterable, self._export_receipts)
  File "/mnt/ethereum-etl/ethereumetl/executors/batch_work_executor.py", line 22, in execute
    self.executor.submit(self._fail_safe_execute, work_handler, batch)
  File "/mnt/ethereum-etl/ethereumetl/executors/fail_safe_executor.py", line 8, in submit
    self._check_completed_futures()
  File "/mnt/ethereum-etl/ethereumetl/executors/fail_safe_executor.py", line 24, in _check_completed_futures
    future.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mnt/ethereum-etl/ethereumetl/executors/batch_work_executor.py", line 41, in _fail_safe_execute
    raise ex
  File "/mnt/ethereum-etl/ethereumetl/executors/batch_work_executor.py", line 27, in _fail_safe_execute
    work_handler(batch)
  File "/mnt/ethereum-etl/ethereumetl/jobs/export_receipts_job.py", line 46, in _export_receipts
    receipts = [self.receipt_mapper.json_dict_to_receipt(result) for result in results]
  File "/mnt/ethereum-etl/ethereumetl/jobs/export_receipts_job.py", line 46, in <listcomp>
    receipts = [self.receipt_mapper.json_dict_to_receipt(result) for result in results]
  File "/mnt/ethereum-etl/ethereumetl/utils.py", line 25, in rpc_response_batch_to_results
    raise ValueError('result is null in response {}'.format(response_item))
ValueError: result is null in response {'error': {'code': -32602, 'message': 'invalid argument 0: json: cannot unmarshal hex string without 0x prefix into Go value of type common.Hash'}, 'jsonrpc': '2.0', 'id': 0}
```

Not really clear what resulted in this error.

**Comment by medvedev1088** [comment]
Did you also run `extract_csv_column.py` as explained here https://github.com/medvedev1088/ethereum-etl#export_receipts_and_logspy?

**Comment by shayanb** [comment]
Thanks @medvedev1088, that was the issue.
