### ISSUE TITLE
ethtoke 0.01a3 has requirement web~=4.0, byt you'll have web3 4.3.0 wich is incompatible

### ISSUE THREAD

**Issue by RaianeQC** [medvedev1088/ethereum-etl#47]
Traceback (most recent call last):
  File "export_blocks_and_transactions.py", line 4, in <module>
    from ethereumetl.ipc import IPCWrapper
  File "C:\Users\XPS\Documents\Python-Ethereum\ethereum-etl-master\ethereumetl\ipc.py", line 5, in <module>
    from web3.providers.ipc import get_default_ipc_path, PersistantSocket
ModuleNotFoundError: No module named 'web3'

**Comment by medvedev1088** [comment]
Fixed. Try again starting with `pip install -r requirements.txt`

**Comment by RaianeQC** [comment]
Thank you!
